FROM python:3.10
WORKDIR /project/
COPY ./app_streamlit/ /project/app_streamlit/
RUN pip install --no-cache-dir -r /project/app_streamlit/requirements.txt

CMD ["streamlit", "run", "app_streamlit/streamlit.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.fileWatcherType", "none", "--browser.gatherUsageStats", "False"]
      