FROM python:3.10
WORKDIR /project/
COPY ./app_backend/ /project/app_backend/
RUN pip install --no-cache-dir -r /project/app_backend/requirements.txt

CMD ["python", "app_backend/api_llama2.py", "--host=0.0.0.0", "--llama-api=http://candidate_chatai-llama_cpp:8080"]

